f = open('24 (4).txt').readline()
a = []

for i in range (len(f)-1):
    if f[i] == 'A':
        a.append(f[i+1])

print(str(a.count('A')) + ' - A')
print(str(a.count('B')) + ' - B')
print(str(a.count('C')) + ' - C')
print(str(a.count('D')) + ' - D')
print(str(a.count('E')) + ' - E')
print(str(a.count('F')) + ' - F')
print(str(a.count('G')) + ' - G')
print(str(a.count('H')) + ' - H')
print(str(a.count('I')) + ' - I')
print(str(a.count('J')) + ' - J')
print(str(a.count('K')) + ' - K')
print(str(a.count('L')) + ' - L')
print(str(a.count('M')) + ' - M')
print(str(a.count('N')) + ' - N')
print(str(a.count('O')) + ' - O')
print(str(a.count('P')) + ' - P')
print(str(a.count('Q')) + ' - Q')
print(str(a.count('R')) + ' - R')
print(str(a.count('S')) + ' - S')
print(str(a.count('T')) + ' - T')
print(str(a.count('U')) + ' - U')
print(str(a.count('V')) + ' - V')
print(str(a.count('W')) + ' - W')
print(str(a.count('X')) + ' - X')
print(str(a.count('Y')) + ' - Y')
print(str(a.count('Z')) + ' - Z')        